### PR TITLE
Added solutions to LeetCode #724 & #1480

### PR DESCRIPTION
**Pull request by rivendesh**

### CODE REVIEW

**Comment by ShlokMohanty** [comment]
@0xVolt i had a doubt that we we are not starting iteration from the 0th element and why from 1st element of the vector ?

**Comment by ShlokMohanty** [comment]
@0xVolt  can we do like this like if we say that we are having two pointers one pointer is moving from the very first index towards the nth element and the second pointer moves from the nth element to the very first element like we would stop both the pointers once we find out the left and right sum are the same and then we would calculate the mid element and then would print its index ?

**Comment by ShlokMohanty** [comment]
// 1 7 3 6 5 6 
// left_sum = nums[0] + nums[1] + nums[2] 
// left_sum = 1+7+3 = 11
// right_sum = 6+5 = 11
// left_sum + right_sum / 2 = 22/2 =11
// 
something like this ?

**Comment by ShlokMohanty** [comment]
@0xVolt have you run this code in your leetcode platform ?

**Comment by ShlokMohanty** [comment]
class Solution {
public:
    int pivotIndex(vector<int>& nums) {
        int i;
    for( i = 1; i < nums.size(); i++)
        nums[i] += nums[i - 1];
            for(auto i : nums)
            {
                cout << i << " ";
    }
        return i;
    }
};
// 1 7 3 6 5 6 
// left_sum = nums[0] + nums[1] + nums[2] 
// left_sum = 1+7+3 = 11
// right_sum = 6+5 = 11
// left_sum + right_sum / 2 = 22/2 =11
//

**Comment by ShlokMohanty** [comment]
please rectify me if i have made something wrong in the code above i have applied your logic only 
in[i] = in[i-1]
and we are printing the index i right ?

**Comment by rivendesh** [comment]
Hey @ShlokMohanty, so a couple of things to clarify. These script files aren't the actual submissions I made on LeetCode. 

> @0xVolt have you run this code in your leetcode platform ?

These files have a `main` function that calls a function `solve()`. The code contained in `solve()` is the actual submission code for the problem. I've used this approach to test my code for various test cases as a CLI input to the program to save time while debugging. If you need to check the code that I submitted, it's in the `solve()` function.

> @0xVolt i had a doubt that we we are not starting iteration from the 0th element and why from 1st element of the vector ?

For the solution to `running-sum`, I figured out that when we create a sum array, we start from the second index, i.e., `i = 1` since we need the value of `i - 1`. That statement becomes problematic if we start from `i = 0` since `0 - 1` is `out of bounds` so to speak.

> please rectify me if i have made something wrong in the code above i have applied your logic only in[i] = in[i-1] and we are printing the index i right ?

Yep, the problem required that we print the index. 

> @0xVolt can we do like this like if we say that we are having two pointers one pointer is moving from the very first index towards the nth element and the second pointer moves from the nth element to the very first element like we would stop both the pointers once we find out the left and right sum are the same and then we would calculate the mid element and then would print its index ?

So this solution would work and it's kinda what I presented in the first solution I made. But the problem is the time complexity. This process needs to run for each element in our vector hence making it an O(n2) problem in its worst case. The solution I have is simpler since we don't traverse the entire vector when passing through it. We simply add and subtract since we need to calculate the cumulative sum and difference through the elements.

**Pull request closed without merging**
